
my_robot_1: 

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

 
  left_steer_velocity_controller:
    type: position_controllers/JointPositionController
    joint: front_left_steer_joint
    #pid: {p: 100, i: 0.1, d: 0.1}
  right_steer_velocity_controller:
    type: position_controllers/JointPositionController
    joint: front_right_steer_joint
    #pid: {p: , i: 0.1, d: 100}  
  back_left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    #pid: {p: 00.1, i: 0.00001, d: 0.0001}  
  back_right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
    #pid: {p: 00.1, i: 0.00001, d: 0.0001}    
  gazebo_ros_control:

    pid_gains:
      front_left_steer_joint: {p: 10, i: 0.00001, d: 0.00001}
      front_right_steer_joint: {p: 10, i: 0.0001, d: 0.0001}
      back_left_wheel_joint: {p: 10, i: 0.00001, d: 0.0001}
      back_right_wheel_joint: {p: 10, i: 0.00001, d: 0.0001}     

   
  
    
  



 

  
