gazebo_ros_control:
  pid_gains:
      front_left_steer_joint:
        pid: {p: 1000, i: 0.1, d: 100}
      
      front_right_steer_joint:
        pid: {p: 1000, i: 0.1, d: 100}
      back_left_wheel_joint:
        pid: {p: 1000, i: 0.1, d: 100}
      back_right_wheel_joint:
         pid: {p: 1000, i: 0.1, d: 100}


